# Exercício:

## 01 – Obtenha os resultados e retorne o objeto e código em Python dos seguintes cálculos:
a) 2.0 + 3.0 / 5.0

b) (a + 10.2) - 5.0 * 2.0

c) a / b + 33.8

d) a / (b + c)

e) d * 2

In [5]:
NUM1 = (2.0)
NUM2 = (3.0)
NUM3 = (5.0)
NUM1 + NUM2 / NUM3

2.6

In [6]:
NUM4 = (2.6)
(NUM4 + 10.2) - 5.0 * 2.0

2.799999999999999

In [7]:
NUM5 = (2.799999999999999)
NUM4 / NUM5 + 33.8

34.72857142857143

In [8]:
NUM6 = (34.72857142857143)
NUM4 / (NUM5 + NUM6)

0.0692805481537876

In [9]:
NUM7 = (0.0692805481537876)
NUM7 * 2

0.1385610963075752

In [39]:
NUM8 = (0.1385610963075752)

## 02 – Obtenha os resultados e retorne o código do objeto em Python dos seguintes cálculos:
a) [2.0, 3.0, 5.0] + [10, 20, 30]

b) lista_a * 2

c) lista_a + lista_b

d) lista_a / (lista_b * lista_c)

In [22]:
import pandas as pd
import numpy as np
LISTA1 = [2.0, 3.0, 5.0]
LISTA2 = [10, 20, 30]
LISTA1 + LISTA2


[2.0, 3.0, 5.0, 10, 20, 30]

In [17]:
lISTA_A = [2.0, 3.0, 5.0, 10, 20, 30] 
lISTA_A * 2

[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

In [19]:
LISTA_B = [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]
lISTA_A + LISTA_B

[2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30]

In [ ]:
LISTA_C = [2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30,
 2.0,
 3.0,
 5.0,
 10,
 20,
 30]

lISTA_A / (LISTA_B * LISTA_C)


[2.0, 3.0, 5.0, 10, 20, 30]
[2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]


TypeError: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01 (a, b, c, d, e), instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [41]:
LISTAS = [NUM4, NUM5, NUM6, NUM7, NUM8]
LISTAS

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [53]:
lista_duplicada = LISTAS * 2
array = np.array(lista_duplicada)
array_reshape = np.resize(array, (5, 4))
print(array_reshape)

[[ 2.6         2.8        34.72857143  0.06928055]
 [ 0.1385611   2.6         2.8        34.72857143]
 [ 0.06928055  0.1385611   2.6         2.8       ]
 [34.72857143  0.06928055  0.1385611   2.6       ]
 [ 2.8        34.72857143  0.06928055  0.1385611 ]]


## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [54]:
array = np.array([[35.5, 15000.0, 0.15, 35.5],
                  [15000.0, 0.15, 35.5, 15000.0],
                  [0.15, 35.5, 15000.0, 0.15],
                  [35.5, 15000.0, 0.15, 35.5],
                  [15000.0, 0.15, 35.5, 15000.0]])
medias_por_coluna = array.mean(axis=0).tolist()

print(medias_por_coluna)

[6014.2300000000005, 6007.160000000001, 3014.2599999999998, 6014.2300000000005]


## 06 – Insira as médias das colunas no final do array do exercício 4.

**Contexto:**
- No exercício 4, você criou um array numpy com 5 linhas e 4 colunas (totalizando 20 valores)
- No exercício 5, você calculou a média de cada uma das 4 colunas (resultando em uma lista com 4 valores)

**Tarefa:**
1. Use o atributo `shape` do array do exercício 4 para calcular o número total de elementos.
2. Insira a lista de médias (do exercício 5) no final de outro array criado
3. Recupere e exiba o array resultante


Obs.:  Atributos não usam () na chamada.

In [55]:
import numpy as np
array_ex4 = np.array([[35.5, 15000.0, 0.15, 35.5],
                      [15000.0, 0.15, 35.5, 15000.0],
                      [0.15, 35.5, 15000.0, 0.15],
                      [35.5, 15000.0, 0.15, 35.5],
                      [15000.0, 0.15, 35.5, 15000.0]])
medias = [6006.23, 6006.23, 6006.23, 6006.23]
total_elementos = array_ex4.shape[0] * array_ex4.shape[1]
array_com_medias = np.append(array_ex4, [medias], axis=0)
print(array_com_medias)

[[3.55000e+01 1.50000e+04 1.50000e-01 3.55000e+01]
 [1.50000e+04 1.50000e-01 3.55000e+01 1.50000e+04]
 [1.50000e-01 3.55000e+01 1.50000e+04 1.50000e-01]
 [3.55000e+01 1.50000e+04 1.50000e-01 3.55000e+01]
 [1.50000e+04 1.50000e-01 3.55000e+01 1.50000e+04]
 [6.00623e+03 6.00623e+03 6.00623e+03 6.00623e+03]]


## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [56]:
import numpy as np
import pandas as pd
array_ex6 = np.array([[35.5, 15000.0, 0.15, 35.5],
                      [15000.0, 0.15, 35.5, 15000.0],
                      [0.15, 35.5, 15000.0, 0.15],
                      [35.5, 15000.0, 0.15, 35.5],
                      [15000.0, 0.15, 35.5, 15000.0],
                      [6006.23, 6006.23, 6006.23, 6006.23]])
array_reshape = array_ex6.reshape(-1, 4)
df = pd.DataFrame(array_reshape, columns=['Col1', 'Col2', 'Col3', 'Col4'])
df_arredondado = df.round(3)
print(df_arredondado)

       Col1      Col2      Col3      Col4
0     35.50  15000.00      0.15     35.50
1  15000.00      0.15     35.50  15000.00
2      0.15     35.50  15000.00      0.15
3     35.50  15000.00      0.15     35.50
4  15000.00      0.15     35.50  15000.00
5   6006.23   6006.23   6006.23   6006.23


## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [57]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})
df = df.round(3)
medias_linhas = df.mean(axis=1)
df['Media_Linha'] = medias_linhas
print(df)

       Col1      Col2      Col3      Col4  Media_Linha
0     35.50  15000.00      0.15     35.50    3767.7875
1  15000.00      0.15     35.50  15000.00    7508.9125
2      0.15     35.50  15000.00      0.15    3758.9500
3     35.50  15000.00      0.15     35.50    3767.7875
4  15000.00      0.15     35.50  15000.00    7508.9125
5   6006.23   6006.23   6006.23   6006.23    6006.2300


## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [58]:
import numpy as np
import pandas as pd
df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

df = df.round(3)
df['Media_Linha'] = df.mean(axis=1).round(3)
descricao = df.describe()
ultima_linha = descricao.iloc[-1]
ultima_coluna = df['Media_Linha']
print("DESCRIBE() DO DATAFRAME:")
print(descricao)
print("\n" + "="*60)

print("\nÚLTIMA LINHA DO DESCRIBE() - Contagem/estatísticas finais:")
print(ultima_linha)
print("\n" + "="*60)

print("\nÚLTIMA COLUNA DO DATAFRAME (Média das Linhas):")
print(ultima_coluna)
print("\n" + "="*60)
print("\nCOMPARAÇÃO ENTRE ÚLTIMA LINHA E ÚLTIMA COLUNA:")
print("-"*40)
print(f"Valor médio da última coluna (Media_Linha): {df['Media_Linha'].mean():.3f}")
print(f"Valor médio da última linha do describe(): {ultima_linha.mean():.3f}")
print("\n" + "="*60)
print("DATAFRAME TRANSPOSTO (transpose):")
print(df.T)

DESCRIBE() DO DATAFRAME:
               Col1          Col2          Col3          Col4  Media_Linha
count      6.000000      6.000000      6.000000      6.000000     6.000000
mean    6012.896667   6007.005000   3512.921667   6012.896667  5386.430000
std     7336.862564   7342.634468   6116.103458   7336.862564  1859.177599
min        0.150000      0.150000      0.150000      0.150000  3758.950000
25%       35.500000      8.987500      8.987500     35.500000  3767.788000
50%     3020.865000   3020.865000     35.500000   3020.865000  4887.009000
75%    12751.557500  12751.557500   4513.547500  12751.557500  7133.241500
max    15000.000000  15000.000000  15000.000000  15000.000000  7508.912000


ÚLTIMA LINHA DO DESCRIBE() - Contagem/estatísticas finais:
Col1           15000.000
Col2           15000.000
Col3           15000.000
Col4           15000.000
Media_Linha     7508.912
Name: max, dtype: float64


ÚLTIMA COLUNA DO DATAFRAME (Média das Linhas):
0    3767.788
1    7508.912
2    3758.9

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [59]:
import pandas as pd
df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})
df.columns = ['C1_Media', 'C2_Media', 'C3_Media', 'C4_Media']
df.index = ['L1', 'L2', 'L3', 'L4', 'L5', 'Media_Cols']
media_geral = df.loc['Media_Cols'].mean()
print(f"Média das médias: {media_geral:.3f}")

Média das médias: 6006.230
