# Exercício:

## 01 – Obtenha os resultados e retorne o código Python dos seguintes cálculos:

<br>a = 2.0 + 3.0 / 5.0 == 10
<br>b = (a + 10.2) - 5.0 * 2.0 <= 2.9
<br>c = 10 <= a / b + 33.8 < 100
<br>d = 5 != a / (b + c)
<br>e = 33 == d * 2

In [12]:
import numpy as np
import pandas as pd
a = 2.0 + 3.0 / 5.0 == 10
print(a)

False


In [13]:
b = (a + 10.2) - 5.0 * 2.0 <= 2.9
print(b)

True


In [14]:
c = 10 <= a / b + 33.8 < 100
print(c)

True


In [15]:
d = 5 != a / (b + c)
print(d)

True


In [16]:
e = 33 == d * 2
print(e)

False


## 02 – Altere os operadores relacionais para modificar o resultado de cada uma das comparações.

<br>('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>['a',1,True,'b',0,False] > ['a',True,1]
<br>['a',1,True,'b',0,False] == 1
<br>['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [17]:
p = ('a',1,True,'b',0,False) == ('a',True,1,'b',False,0)
print(p) 
q = ['a',1,True,'b',0,False] == ('a',True,1,'b',False,0)
print(q)  
r = ['a',1,True,'b',0,False] == ['a',True,1,'b',False,0]
print(r)  
s = ['a',1,True,'b',0,False] <= ['a',True,1]
print(s) 
t = ['a',1,True,'b',0,False] != 1
print(t)  
u = ['a',True,1] > ['a',True,1] > ['a',1,True,'b',0,False]
print(u)  

True
False
True
False
True
False


## 03 – Usando o método DataFrame.to_csv(‘nome_do_arquivo.csv’) exporte o objeto obtido no exercício 10 da aula anterior para um arquivo CSV. Usando o método pd.read_csv(‘nome_do_arquivo.csv’) instancie uma DataFrame. Use o valor ‘Unnamed: 0’ no parâmetro index_col, para ajustar o index. Arredonde os valores para até três casas decimais, usando o método round().
Recupere a DataFrame.

In [18]:
import pandas as pd
df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})
df['Media_Linha'] = df.mean(axis=1)
df = df.round(3)
df.to_csv('dados.csv')
df_importado = pd.read_csv('dados.csv', index_col='Unnamed: 0')
df_importado = df_importado.round(3)
print(df_importado)

       Col1      Col2      Col3      Col4  Media_Linha
0     35.50  15000.00      0.15     35.50     3767.788
1  15000.00      0.15     35.50  15000.00     7508.912
2      0.15     35.50  15000.00      0.15     3758.950
3     35.50  15000.00      0.15     35.50     3767.788
4  15000.00      0.15     35.50  15000.00     7508.912
5   6006.23   6006.23   6006.23   6006.23     6006.230


## 04 – Instancie um numpy array que apresente o mesmo formato (linhas e colunas) da DataFrame. Este array deve conter apenas inteiros uns.
Recupere o array.

Obs.: Procure na internet o método numpy.ones()

In [19]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

array_ones = np.ones(shape=(df.shape[0], df.shape[1]), dtype=int)

print(array_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 05 – Quantos dos valores contidos na DataFrame são iguais aos valores no array?

In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

array_ones = np.ones(shape=(df.shape[0], df.shape[1]), dtype=int)

iguais = (df.values == array_ones).sum()

print(iguais)

0


## 06 – Quantos dos valores contidos na DataFrame são superiores aos valores no array?

In [21]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

array_ones = np.ones(shape=(df.shape[0], df.shape[1]), dtype=int)

superiores = (df.values > array_ones).sum()

print(superiores)

18


## 07 – Quantos dos valores contidos na DataFrame são iguais ou inferiores aos valores no array?

In [22]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})
array_ones = np.ones(shape=(df.shape[0], df.shape[1]), dtype=int)
iguais_ou_inferiores = (df.values <= array_ones).sum()
print(iguais_ou_inferiores)

6


## 08 – Quantos dos valores contidos na DataFrame estão entre 0 e 1?

In [23]:
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

entre_0_e_1 = ((df > 0) & (df < 1)).sum().sum()

print(entre_0_e_1)

6


## 09 – Quantos dos valores das médias das linhas são inferiores ou iguais à 5?

Obs 1.: Usando o método de classe, você pode converter qualquer objeto em outra classe. Ex. obj = list(array)

Obs 2.: Assim com o objeto da classe str, listas também possuem a função count()

In [24]:
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

df['Media_Linha'] = df.mean(axis=1)

medias = list(df['Media_Linha'])

inferiores_ou_iguais = sum(1 for m in medias if m <= 5)

print(inferiores_ou_iguais)

0


## 10 – Quantos dos valores das médias das colunas são superiores à 5?

In [25]:
import pandas as pd

df = pd.DataFrame({
    'Col1': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23],
    'Col2': [15000.0, 0.15, 35.5, 15000.0, 0.15, 6006.23],
    'Col3': [0.15, 35.5, 15000.0, 0.15, 35.5, 6006.23],
    'Col4': [35.5, 15000.0, 0.15, 35.5, 15000.0, 6006.23]
})

medias_colunas = df.mean()

superiores = (medias_colunas > 5).sum()

print(superiores)

4
